name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout public repo
      - uses: actions/checkout@v3

      # Checkout artwork private repo
      - name: Clone private artworks
        uses: actions/checkout@v3
        with:
          repository: Arucaden/daffa-artworks
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: public/artworks   #ignored

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - run: npm ci

      - run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SA }}
          projectId: arucaden
          channelId: live
